wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.8
    cli_version: 0.17.0
    is_jupyter_run: true
    is_kaggle_kernel: false
    start_time: 1716934628
    t:
      1:
      - 55
      - 86
      - 92
      - 95
      - 96
      - 105
      2:
      - 55
      - 86
      - 92
      - 95
      - 96
      - 105
      3:
      - 23
      4: 3.11.8
      5: 0.17.0
      8:
      - 1
      - 4
      - 5
      13: darwin-arm64
